// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_invite_codes.sql

package repo

import (
	"context"
	"database/sql"
)

const countInviteCodes = `-- name: CountInviteCodes :one
SELECT COUNT(*) FROM admin_invite_codes
`

func (q *Queries) CountInviteCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInviteCodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInviteCode = `-- name: CreateInviteCode :one
INSERT INTO admin_invite_codes (code, created_by_admin_id, max_uses, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, code, created_by_admin_id, max_uses, current_uses, expires_at, created_at
`

type CreateInviteCodeParams struct {
	Code             string         `json:"code"`
	CreatedByAdminID int64          `json:"created_by_admin_id"`
	MaxUses          sql.NullInt64  `json:"max_uses"`
	ExpiresAt        sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) (AdminInviteCode, error) {
	row := q.db.QueryRowContext(ctx, createInviteCode,
		arg.Code,
		arg.CreatedByAdminID,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i AdminInviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedByAdminID,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInviteCodes = `-- name: DeleteExpiredInviteCodes :exec
DELETE FROM admin_invite_codes
WHERE expires_at IS NOT NULL 
  AND expires_at < datetime('now')
`

// Cleanup job: Remove expired codes
func (q *Queries) DeleteExpiredInviteCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredInviteCodes)
	return err
}

const deleteInviteCode = `-- name: DeleteInviteCode :exec
DELETE FROM admin_invite_codes
WHERE id = ?
`

func (q *Queries) DeleteInviteCode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInviteCode, id)
	return err
}

const getInviteCodeByCode = `-- name: GetInviteCodeByCode :one
SELECT id, code, created_by_admin_id, max_uses, current_uses, expires_at, created_at
FROM admin_invite_codes
WHERE code = ?
LIMIT 1
`

func (q *Queries) GetInviteCodeByCode(ctx context.Context, code string) (AdminInviteCode, error) {
	row := q.db.QueryRowContext(ctx, getInviteCodeByCode, code)
	var i AdminInviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedByAdminID,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteCodeByID = `-- name: GetInviteCodeByID :one
SELECT id, code, created_by_admin_id, max_uses, current_uses, expires_at, created_at
FROM admin_invite_codes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetInviteCodeByID(ctx context.Context, id int64) (AdminInviteCode, error) {
	row := q.db.QueryRowContext(ctx, getInviteCodeByID, id)
	var i AdminInviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedByAdminID,
		&i.MaxUses,
		&i.CurrentUses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteCodeUses = `-- name: IncrementInviteCodeUses :exec
UPDATE admin_invite_codes
SET current_uses = current_uses + 1
WHERE id = ?
`

func (q *Queries) IncrementInviteCodeUses(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementInviteCodeUses, id)
	return err
}

const listInviteCodes = `-- name: ListInviteCodes :many
SELECT id, code, created_by_admin_id, max_uses, current_uses, expires_at, created_at
FROM admin_invite_codes
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListInviteCodesParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

// Admin: List all invite codes with pagination
func (q *Queries) ListInviteCodes(ctx context.Context, arg ListInviteCodesParams) ([]AdminInviteCode, error) {
	rows, err := q.db.QueryContext(ctx, listInviteCodes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminInviteCode{}
	for rows.Next() {
		var i AdminInviteCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedByAdminID,
			&i.MaxUses,
			&i.CurrentUses,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
