// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import.sql

package repo

import (
	"context"
	"database/sql"
)

const countPatterns = `-- name: CountPatterns :one
SELECT COUNT(*) as count FROM patterns
`

// Get total pattern count
func (q *Queries) CountPatterns(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPatterns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblems = `-- name: CountProblems :one
SELECT COUNT(*) as count FROM problems
`

// Get total problem count
func (q *Queries) CountProblems(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPatternByTitle = `-- name: GetPatternByTitle :one

SELECT id, title, description FROM patterns 
WHERE LOWER(title) = LOWER(?) 
LIMIT 1
`

// Import-specific queries for bulk operations
// Case-insensitive pattern lookup
func (q *Queries) GetPatternByTitle(ctx context.Context, lower string) (Pattern, error) {
	row := q.db.QueryRowContext(ctx, getPatternByTitle, lower)
	var i Pattern
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getProblemByTitleAndSource = `-- name: GetProblemByTitleAndSource :one
SELECT id, title, source, url, difficulty, created_at FROM problems 
WHERE title = ? AND source = ? 
LIMIT 1
`

type GetProblemByTitleAndSourceParams struct {
	Title  string         `json:"title"`
	Source sql.NullString `json:"source"`
}

// Check for duplicate problems
func (q *Queries) GetProblemByTitleAndSource(ctx context.Context, arg GetProblemByTitleAndSourceParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByTitleAndSource, arg.Title, arg.Source)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemByTitleSourceURL = `-- name: GetProblemByTitleSourceURL :one
SELECT id, title, source, url, difficulty, created_at FROM problems 
WHERE title = ? AND (source = ? OR (source IS NULL AND ? IS NULL))
LIMIT 1
`

type GetProblemByTitleSourceURLParams struct {
	Title   string         `json:"title"`
	Source  sql.NullString `json:"source"`
	Column3 interface{}    `json:"column_3"`
}

// More precise duplicate check including URL
func (q *Queries) GetProblemByTitleSourceURL(ctx context.Context, arg GetProblemByTitleSourceURLParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblemByTitleSourceURL, arg.Title, arg.Source, arg.Column3)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const linkProblemToPatternIfNotExists = `-- name: LinkProblemToPatternIfNotExists :exec
INSERT OR IGNORE INTO problem_patterns (problem_id, pattern_id)
VALUES (?, ?)
`

type LinkProblemToPatternIfNotExistsParams struct {
	ProblemID int64 `json:"problem_id"`
	PatternID int64 `json:"pattern_id"`
}

// Idempotent pattern linking (ignore if already linked)
func (q *Queries) LinkProblemToPatternIfNotExists(ctx context.Context, arg LinkProblemToPatternIfNotExistsParams) error {
	_, err := q.db.ExecContext(ctx, linkProblemToPatternIfNotExists, arg.ProblemID, arg.PatternID)
	return err
}
