// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
)

type Pattern struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

type Problem struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Source     sql.NullString `json:"source"`
	Url        sql.NullString `json:"url"`
	Difficulty sql.NullString `json:"difficulty"`
	CreatedAt  sql.NullString `json:"created_at"`
}

type ProblemPattern struct {
	ProblemID int64 `json:"problem_id"`
	PatternID int64 `json:"pattern_id"`
}

type RefreshToken struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt sql.NullString `json:"created_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

type RevisionSession struct {
	ID                 int64          `json:"id"`
	UserID             int64          `json:"user_id"`
	TemplateKey        sql.NullString `json:"template_key"`
	CreatedAt          sql.NullString `json:"created_at"`
	PlannedDurationMin sql.NullInt64  `json:"planned_duration_min"`
	ItemsOrdered       sql.NullString `json:"items_ordered"`
}

type User struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	CreatedAt    sql.NullString `json:"created_at"`
}

type UserPatternStat struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	PatternID     int64          `json:"pattern_id"`
	TimesRevised  sql.NullInt64  `json:"times_revised"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastRevisedAt sql.NullString `json:"last_revised_at"`
}

type UserProblemStat struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	ProblemID       int64          `json:"problem_id"`
	Status          sql.NullString `json:"status"`
	Confidence      sql.NullInt64  `json:"confidence"`
	AvgConfidence   sql.NullInt64  `json:"avg_confidence"`
	LastAttemptAt   sql.NullString `json:"last_attempt_at"`
	TotalAttempts   sql.NullInt64  `json:"total_attempts"`
	AvgTimeSeconds  sql.NullInt64  `json:"avg_time_seconds"`
	LastOutcome     sql.NullString `json:"last_outcome"`
	RevisionHistory sql.NullString `json:"revision_history"`
	UpdatedAt       sql.NullString `json:"updated_at"`
}
