// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql"
)

type AdminInviteCode struct {
	ID               int64          `json:"id"`
	Code             string         `json:"code"`
	CreatedByAdminID int64          `json:"created_by_admin_id"`
	MaxUses          sql.NullInt64  `json:"max_uses"`
	CurrentUses      sql.NullInt64  `json:"current_uses"`
	ExpiresAt        sql.NullString `json:"expires_at"`
	CreatedAt        sql.NullString `json:"created_at"`
}

type Attempt struct {
	ID                 int64          `json:"id"`
	UserID             int64          `json:"user_id"`
	ProblemID          int64          `json:"problem_id"`
	SessionID          sql.NullInt64  `json:"session_id"`
	ConfidenceScore    sql.NullInt64  `json:"confidence_score"`
	DurationSeconds    sql.NullInt64  `json:"duration_seconds"`
	Outcome            sql.NullString `json:"outcome"`
	Notes              sql.NullString `json:"notes"`
	PerformedAt        sql.NullString `json:"performed_at"`
	Status             sql.NullString `json:"status"`
	ElapsedTimeSeconds sql.NullInt64  `json:"elapsed_time_seconds"`
	TimerState         sql.NullString `json:"timer_state"`
	TimerLastUpdatedAt sql.NullString `json:"timer_last_updated_at"`
	StartedAt          sql.NullString `json:"started_at"`
}

type PasswordResetToken struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	TokenHash        string         `json:"token_hash"`
	CreatedByAdminID sql.NullInt64  `json:"created_by_admin_id"`
	ExpiresAt        string         `json:"expires_at"`
	UsedAt           sql.NullString `json:"used_at"`
	CreatedAt        sql.NullString `json:"created_at"`
}

type Pattern struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

type Problem struct {
	ID         int64          `json:"id"`
	Title      string         `json:"title"`
	Source     sql.NullString `json:"source"`
	Url        sql.NullString `json:"url"`
	Difficulty sql.NullString `json:"difficulty"`
	CreatedAt  sql.NullString `json:"created_at"`
}

type ProblemPattern struct {
	ProblemID int64 `json:"problem_id"`
	PatternID int64 `json:"pattern_id"`
}

type RefreshToken struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt string         `json:"expires_at"`
	CreatedAt sql.NullString `json:"created_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

type RevisionSession struct {
	ID                 int64          `json:"id"`
	UserID             int64          `json:"user_id"`
	TemplateKey        sql.NullString `json:"template_key"`
	SessionName        sql.NullString `json:"session_name"`
	IsCustom           sql.NullBool   `json:"is_custom"`
	CustomConfigJson   sql.NullString `json:"custom_config_json"`
	CreatedAt          sql.NullString `json:"created_at"`
	CompletedAt        sql.NullString `json:"completed_at"`
	PlannedDurationMin sql.NullInt64  `json:"planned_duration_min"`
	ItemsOrdered       sql.NullString `json:"items_ordered"`
	ElapsedTimeSeconds sql.NullInt64  `json:"elapsed_time_seconds"`
	TimerState         sql.NullString `json:"timer_state"`
	TimerLastUpdatedAt sql.NullString `json:"timer_last_updated_at"`
}

type SystemSetting struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
	UpdatedAt   sql.NullString `json:"updated_at"`
}

type User struct {
	ID           int64          `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	Name         string         `json:"name"`
	Role         sql.NullString `json:"role"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullString `json:"created_at"`
}

type UserPatternMilestone struct {
	ID               int64          `json:"id"`
	UserID           int64          `json:"user_id"`
	PatternID        int64          `json:"pattern_id"`
	MilestoneType    sql.NullString `json:"milestone_type"`
	ConfidenceBefore sql.NullInt64  `json:"confidence_before"`
	ConfidenceAfter  sql.NullInt64  `json:"confidence_after"`
	Notes            sql.NullString `json:"notes"`
	AchievedAt       sql.NullString `json:"achieved_at"`
	SessionID        sql.NullInt64  `json:"session_id"`
}

type UserPatternStat struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	PatternID     int64          `json:"pattern_id"`
	TimesRevised  sql.NullInt64  `json:"times_revised"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastRevisedAt sql.NullString `json:"last_revised_at"`
}

type UserProblemStat struct {
	ID                int64          `json:"id"`
	UserID            int64          `json:"user_id"`
	ProblemID         int64          `json:"problem_id"`
	Status            sql.NullString `json:"status"`
	Confidence        sql.NullInt64  `json:"confidence"`
	AvgConfidence     sql.NullInt64  `json:"avg_confidence"`
	LastAttemptAt     sql.NullString `json:"last_attempt_at"`
	TotalAttempts     sql.NullInt64  `json:"total_attempts"`
	AvgTimeSeconds    sql.NullInt64  `json:"avg_time_seconds"`
	LastOutcome       sql.NullString `json:"last_outcome"`
	RecentHistoryJson sql.NullString `json:"recent_history_json"`
	UpdatedAt         sql.NullString `json:"updated_at"`
}

type UserSessionTemplate struct {
	ID           int64          `json:"id"`
	UserID       int64          `json:"user_id"`
	TemplateName string         `json:"template_name"`
	TemplateKey  sql.NullString `json:"template_key"`
	ConfigJson   string         `json:"config_json"`
	CreatedAt    sql.NullString `json:"created_at"`
	UpdatedAt    sql.NullString `json:"updated_at"`
	LastUsedAt   sql.NullString `json:"last_used_at"`
	UseCount     sql.NullInt64  `json:"use_count"`
	IsFavorite   sql.NullBool   `json:"is_favorite"`
}
