// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package repo

import (
	"context"
	"database/sql"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (user_id, token_hash, created_by_admin_id, expires_at)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, token_hash, created_by_admin_id, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID           int64         `json:"user_id"`
	TokenHash        string        `json:"token_hash"`
	CreatedByAdminID sql.NullInt64 `json:"created_by_admin_id"`
	ExpiresAt        string        `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, createPasswordResetToken,
		arg.UserID,
		arg.TokenHash,
		arg.CreatedByAdminID,
		arg.ExpiresAt,
	)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedByAdminID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < datetime('now')
`

// Cleanup job: Remove expired tokens
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens
WHERE id = ?
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetToken, id)
	return err
}

const deleteUsedPasswordResetTokens = `-- name: DeleteUsedPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE used_at IS NOT NULL
`

// Cleanup job: Remove tokens that were already used
func (q *Queries) DeleteUsedPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUsedPasswordResetTokens)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token_hash, created_by_admin_id, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = ?
LIMIT 1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedByAdminID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, id)
	return err
}
