// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patterns.sql

package repo

import (
	"context"
	"database/sql"
	"strings"
)

const createPattern = `-- name: CreatePattern :one
INSERT INTO patterns (title, description)
VALUES (?, ?)
RETURNING id, title, description
`

type CreatePatternParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreatePattern(ctx context.Context, arg CreatePatternParams) (Pattern, error) {
	row := q.db.QueryRowContext(ctx, createPattern, arg.Title, arg.Description)
	var i Pattern
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getPattern = `-- name: GetPattern :one
SELECT id, title, description FROM patterns
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPattern(ctx context.Context, id int64) (Pattern, error) {
	row := q.db.QueryRowContext(ctx, getPattern, id)
	var i Pattern
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getPatternsByIDs = `-- name: GetPatternsByIDs :many
SELECT id, title, description FROM patterns
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) GetPatternsByIDs(ctx context.Context, ids []int64) ([]Pattern, error) {
	query := getPatternsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pattern{}
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatterns = `-- name: ListPatterns :many
SELECT id, title, description FROM patterns
ORDER BY title
`

func (q *Queries) ListPatterns(ctx context.Context) ([]Pattern, error) {
	rows, err := q.db.QueryContext(ctx, listPatterns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pattern{}
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
