// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package repo

import (
	"context"
	"database/sql"
)

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (title, source, url, difficulty)
VALUES (?, ?, ?, ?)
RETURNING id, title, source, url, difficulty, created_at
`

type CreateProblemParams struct {
	Title      string         `json:"title"`
	Source     sql.NullString `json:"source"`
	Url        sql.NullString `json:"url"`
	Difficulty sql.NullString `json:"difficulty"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.Title,
		arg.Source,
		arg.Url,
		arg.Difficulty,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblemPatterns = `-- name: DeleteProblemPatterns :exec
DELETE FROM problem_patterns
WHERE problem_id = ?
`

func (q *Queries) DeleteProblemPatterns(ctx context.Context, problemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProblemPatterns, problemID)
	return err
}

const getPatternsForProblem = `-- name: GetPatternsForProblem :many
SELECT p.id, p.title, p.description
FROM patterns p
JOIN problem_patterns pp ON p.id = pp.pattern_id
WHERE pp.problem_id = ?
`

func (q *Queries) GetPatternsForProblem(ctx context.Context, problemID int64) ([]Pattern, error) {
	rows, err := q.db.QueryContext(ctx, getPatternsForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pattern{}
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblem = `-- name: GetProblem :one
SELECT id, title, source, url, difficulty, created_at FROM problems
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProblem(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const linkProblemToPattern = `-- name: LinkProblemToPattern :exec
INSERT INTO problem_patterns (problem_id, pattern_id)
VALUES (?, ?)
`

type LinkProblemToPatternParams struct {
	ProblemID int64 `json:"problem_id"`
	PatternID int64 `json:"pattern_id"`
}

func (q *Queries) LinkProblemToPattern(ctx context.Context, arg LinkProblemToPatternParams) error {
	_, err := q.db.ExecContext(ctx, linkProblemToPattern, arg.ProblemID, arg.PatternID)
	return err
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, source, url, difficulty, created_at FROM problems
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProblemsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProblems(ctx context.Context, arg ListProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
