// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package repo

import (
	"context"
	"database/sql"
)

const countProblemsForUser = `-- name: CountProblemsForUser :one
SELECT COUNT(DISTINCT p.id) as count
FROM problems p
LEFT JOIN user_problem_stats ups ON p.id = ups.problem_id AND ups.user_id = ?1
WHERE (?2 = '' OR p.title LIKE '%' || ?2 || '%' OR p.source LIKE '%' || ?2 || '%')
  AND (?3 = '' OR p.difficulty = ?3)
  AND (?4 = '' OR ups.status = ?4 OR (ups.status IS NULL AND ?4 = 'unsolved'))
`

type CountProblemsForUserParams struct {
	UserID      int64       `json:"user_id"`
	SearchQuery interface{} `json:"search_query"`
	Difficulty  interface{} `json:"difficulty"`
	Status      interface{} `json:"status"`
}

func (q *Queries) CountProblemsForUser(ctx context.Context, arg CountProblemsForUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProblemsForUser,
		arg.UserID,
		arg.SearchQuery,
		arg.Difficulty,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblem = `-- name: CreateProblem :one
INSERT INTO problems (title, source, url, difficulty)
VALUES (?, ?, ?, ?)
RETURNING id, title, source, url, difficulty, created_at
`

type CreateProblemParams struct {
	Title      string         `json:"title"`
	Source     sql.NullString `json:"source"`
	Url        sql.NullString `json:"url"`
	Difficulty sql.NullString `json:"difficulty"`
}

func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, createProblem,
		arg.Title,
		arg.Source,
		arg.Url,
		arg.Difficulty,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM problems
WHERE id = ?
`

func (q *Queries) DeleteProblem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProblem, id)
	return err
}

const deleteProblemPatterns = `-- name: DeleteProblemPatterns :exec
DELETE FROM problem_patterns
WHERE problem_id = ?
`

func (q *Queries) DeleteProblemPatterns(ctx context.Context, problemID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProblemPatterns, problemID)
	return err
}

const getPatternsForProblem = `-- name: GetPatternsForProblem :many
SELECT p.id, p.title, p.description
FROM patterns p
JOIN problem_patterns pp ON p.id = pp.pattern_id
WHERE pp.problem_id = ?
`

func (q *Queries) GetPatternsForProblem(ctx context.Context, problemID int64) ([]Pattern, error) {
	rows, err := q.db.QueryContext(ctx, getPatternsForProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Pattern{}
	for rows.Next() {
		var i Pattern
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProblem = `-- name: GetProblem :one
SELECT id, title, source, url, difficulty, created_at FROM problems
WHERE id = ? LIMIT 1
`

func (q *Queries) GetProblem(ctx context.Context, id int64) (Problem, error) {
	row := q.db.QueryRowContext(ctx, getProblem, id)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}

const getProblemsForUser = `-- name: GetProblemsForUser :many
SELECT p.id, p.title, p.source, p.url, p.difficulty, p.created_at, ups.status, ups.confidence, ups.avg_confidence, 
       ups.last_attempt_at, ups.total_attempts, ups.last_outcome, ups.updated_at
FROM problems p
LEFT JOIN user_problem_stats ups ON p.id = ups.problem_id AND ups.user_id = ?
ORDER BY p.created_at DESC
`

type GetProblemsForUserRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Source        sql.NullString `json:"source"`
	Url           sql.NullString `json:"url"`
	Difficulty    sql.NullString `json:"difficulty"`
	CreatedAt     sql.NullString `json:"created_at"`
	Status        sql.NullString `json:"status"`
	Confidence    sql.NullInt64  `json:"confidence"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	TotalAttempts sql.NullInt64  `json:"total_attempts"`
	LastOutcome   sql.NullString `json:"last_outcome"`
	UpdatedAt     sql.NullString `json:"updated_at"`
}

func (q *Queries) GetProblemsForUser(ctx context.Context, userID int64) ([]GetProblemsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getProblemsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProblemsForUserRow{}
	for rows.Next() {
		var i GetProblemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.Difficulty,
			&i.CreatedAt,
			&i.Status,
			&i.Confidence,
			&i.AvgConfidence,
			&i.LastAttemptAt,
			&i.TotalAttempts,
			&i.LastOutcome,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkProblemToPattern = `-- name: LinkProblemToPattern :exec
INSERT INTO problem_patterns (problem_id, pattern_id)
VALUES (?, ?)
`

type LinkProblemToPatternParams struct {
	ProblemID int64 `json:"problem_id"`
	PatternID int64 `json:"pattern_id"`
}

func (q *Queries) LinkProblemToPattern(ctx context.Context, arg LinkProblemToPatternParams) error {
	_, err := q.db.ExecContext(ctx, linkProblemToPattern, arg.ProblemID, arg.PatternID)
	return err
}

const listAllProblems = `-- name: ListAllProblems :many
SELECT id, title, source, url, difficulty, created_at FROM problems
ORDER BY created_at DESC
`

func (q *Queries) ListAllProblems(ctx context.Context) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listAllProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, title, source, url, difficulty, created_at FROM problems
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListProblemsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListProblems(ctx context.Context, arg ListProblemsParams) ([]Problem, error) {
	rows, err := q.db.QueryContext(ctx, listProblems, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Problem{}
	for rows.Next() {
		var i Problem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProblemsForUser = `-- name: SearchProblemsForUser :many
SELECT p.id, p.title, p.source, p.url, p.difficulty, p.created_at, ups.status, ups.confidence, ups.avg_confidence, 
       ups.last_attempt_at, ups.total_attempts, ups.last_outcome, ups.updated_at
FROM problems p
LEFT JOIN user_problem_stats ups ON p.id = ups.problem_id AND ups.user_id = ?1
WHERE (?2 = '' OR p.title LIKE '%' || ?2 || '%' OR p.source LIKE '%' || ?2 || '%')
  AND (?3 = '' OR p.difficulty = ?3)
  AND (?4 = '' OR ups.status = ?4 OR (ups.status IS NULL AND ?4 = 'unsolved'))
ORDER BY p.created_at DESC
LIMIT ?6 OFFSET ?5
`

type SearchProblemsForUserParams struct {
	UserID      int64       `json:"user_id"`
	SearchQuery interface{} `json:"search_query"`
	Difficulty  interface{} `json:"difficulty"`
	Status      interface{} `json:"status"`
	OffsetVal   int64       `json:"offset_val"`
	LimitVal    int64       `json:"limit_val"`
}

type SearchProblemsForUserRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Source        sql.NullString `json:"source"`
	Url           sql.NullString `json:"url"`
	Difficulty    sql.NullString `json:"difficulty"`
	CreatedAt     sql.NullString `json:"created_at"`
	Status        sql.NullString `json:"status"`
	Confidence    sql.NullInt64  `json:"confidence"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastAttemptAt sql.NullString `json:"last_attempt_at"`
	TotalAttempts sql.NullInt64  `json:"total_attempts"`
	LastOutcome   sql.NullString `json:"last_outcome"`
	UpdatedAt     sql.NullString `json:"updated_at"`
}

func (q *Queries) SearchProblemsForUser(ctx context.Context, arg SearchProblemsForUserParams) ([]SearchProblemsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProblemsForUser,
		arg.UserID,
		arg.SearchQuery,
		arg.Difficulty,
		arg.Status,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProblemsForUserRow{}
	for rows.Next() {
		var i SearchProblemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.Difficulty,
			&i.CreatedAt,
			&i.Status,
			&i.Confidence,
			&i.AvgConfidence,
			&i.LastAttemptAt,
			&i.TotalAttempts,
			&i.LastOutcome,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProblem = `-- name: UpdateProblem :one
UPDATE problems
SET title = ?, source = ?, url = ?, difficulty = ?
WHERE id = ?
RETURNING id, title, source, url, difficulty, created_at
`

type UpdateProblemParams struct {
	Title      string         `json:"title"`
	Source     sql.NullString `json:"source"`
	Url        sql.NullString `json:"url"`
	Difficulty sql.NullString `json:"difficulty"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) (Problem, error) {
	row := q.db.QueryRowContext(ctx, updateProblem,
		arg.Title,
		arg.Source,
		arg.Url,
		arg.Difficulty,
		arg.ID,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.Difficulty,
		&i.CreatedAt,
	)
	return i, err
}
