// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	// Used for checking if the system has been initialized (seed logic)
	CountUsers(ctx context.Context) (int64, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteExpiredTokens(ctx context.Context) error
	DeleteUser(ctx context.Context, id int64) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GetRefreshTokenByHashRow, error)
	// Used for Login: Fetch everything including the password_hash
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Used for Session/Context: Fetch user details without the sensitive hash
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
