// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repo

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :one
INSERT INTO revision_sessions (user_id, template_key, planned_duration_min, items_ordered)
VALUES (?, ?, ?, ?)
RETURNING id, user_id, template_key, created_at, completed_at, planned_duration_min, items_ordered, session_name, is_custom, custom_config_json
`

type CreateSessionParams struct {
	UserID             int64          `json:"user_id"`
	TemplateKey        sql.NullString `json:"template_key"`
	PlannedDurationMin sql.NullInt64  `json:"planned_duration_min"`
	ItemsOrdered       sql.NullString `json:"items_ordered"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (RevisionSession, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.UserID,
		arg.TemplateKey,
		arg.PlannedDurationMin,
		arg.ItemsOrdered,
	)
	var i RevisionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PlannedDurationMin,
		&i.ItemsOrdered,
		&i.SessionName,
		&i.IsCustom,
		&i.CustomConfigJson,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, template_key, created_at, completed_at, planned_duration_min, items_ordered, session_name, is_custom, custom_config_json FROM revision_sessions
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetSessionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (RevisionSession, error) {
	row := q.db.QueryRowContext(ctx, getSession, arg.ID, arg.UserID)
	var i RevisionSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateKey,
		&i.CreatedAt,
		&i.CompletedAt,
		&i.PlannedDurationMin,
		&i.ItemsOrdered,
		&i.SessionName,
		&i.IsCustom,
		&i.CustomConfigJson,
	)
	return i, err
}

const getSessionCount = `-- name: GetSessionCount :one
SELECT COUNT(*) as count
FROM revision_sessions
WHERE user_id = ?
`

func (q *Queries) GetSessionCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSessionCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, template_key, created_at, completed_at, planned_duration_min, items_ordered, session_name, is_custom, custom_config_json FROM revision_sessions
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsForUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]RevisionSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionSession{}
	for rows.Next() {
		var i RevisionSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateKey,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.PlannedDurationMin,
			&i.ItemsOrdered,
			&i.SessionName,
			&i.IsCustom,
			&i.CustomConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionCompleted = `-- name: UpdateSessionCompleted :exec
UPDATE revision_sessions
SET completed_at = ?
WHERE id = ? AND user_id = ?
`

type UpdateSessionCompletedParams struct {
	CompletedAt sql.NullString `json:"completed_at"`
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
}

func (q *Queries) UpdateSessionCompleted(ctx context.Context, arg UpdateSessionCompletedParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionCompleted, arg.CompletedAt, arg.ID, arg.UserID)
	return err
}
