// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_settings.sql

package repo

import (
	"context"
	"database/sql"
)

const getScoringWeights = `-- name: GetScoringWeights :many
SELECT key, value FROM system_settings
WHERE key IN ('w_conf', 'w_days', 'w_attempts', 'w_time', 'w_difficulty', 'w_failed', 'w_pattern')
`

type GetScoringWeightsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetScoringWeights(ctx context.Context) ([]GetScoringWeightsRow, error) {
	rows, err := q.db.QueryContext(ctx, getScoringWeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScoringWeightsRow{}
	for rows.Next() {
		var i GetScoringWeightsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignupSettings = `-- name: GetSignupSettings :many
SELECT key, value FROM system_settings
WHERE key IN ('signup_enabled', 'invite_codes_enabled')
`

type GetSignupSettingsRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetSignupSettings(ctx context.Context) ([]GetSignupSettingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSignupSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSignupSettingsRow{}
	for rows.Next() {
		var i GetSignupSettingsRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemSetting = `-- name: GetSystemSetting :one
SELECT "key", value, description, updated_at FROM system_settings
WHERE key = ?
LIMIT 1
`

func (q *Queries) GetSystemSetting(ctx context.Context, key string) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSetting, key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listSystemSettings = `-- name: ListSystemSettings :many
SELECT "key", value, description, updated_at FROM system_settings
ORDER BY key
`

func (q *Queries) ListSystemSettings(ctx context.Context) ([]SystemSetting, error) {
	rows, err := q.db.QueryContext(ctx, listSystemSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSetting{}
	for rows.Next() {
		var i SystemSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSystemSetting = `-- name: UpdateSystemSetting :one
UPDATE system_settings
SET value = ?, updated_at = CURRENT_TIMESTAMP
WHERE key = ?
RETURNING "key", value, description, updated_at
`

type UpdateSystemSettingParams struct {
	Value string `json:"value"`
	Key   string `json:"key"`
}

func (q *Queries) UpdateSystemSetting(ctx context.Context, arg UpdateSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, updateSystemSetting, arg.Value, arg.Key)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSystemSetting = `-- name: UpsertSystemSetting :one
INSERT INTO system_settings (key, value, description)
VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
    value = excluded.value,
    updated_at = CURRENT_TIMESTAMP
RETURNING "key", value, description, updated_at
`

type UpsertSystemSettingParams struct {
	Key         string         `json:"key"`
	Value       string         `json:"value"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) UpsertSystemSetting(ctx context.Context, arg UpsertSystemSettingParams) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertSystemSetting, arg.Key, arg.Value, arg.Description)
	var i SystemSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
