// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_session_templates.sql

package repo

import (
	"context"
	"database/sql"
)

const createUserSessionTemplate = `-- name: CreateUserSessionTemplate :one
INSERT INTO user_session_templates (
    user_id,
    template_name,
    template_key,
    config_json,
    is_favorite
) VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, template_name, template_key, config_json, created_at, updated_at, last_used_at, use_count, is_favorite
`

type CreateUserSessionTemplateParams struct {
	UserID       int64          `json:"user_id"`
	TemplateName string         `json:"template_name"`
	TemplateKey  sql.NullString `json:"template_key"`
	ConfigJson   string         `json:"config_json"`
	IsFavorite   sql.NullBool   `json:"is_favorite"`
}

func (q *Queries) CreateUserSessionTemplate(ctx context.Context, arg CreateUserSessionTemplateParams) (UserSessionTemplate, error) {
	row := q.db.QueryRowContext(ctx, createUserSessionTemplate,
		arg.UserID,
		arg.TemplateName,
		arg.TemplateKey,
		arg.ConfigJson,
		arg.IsFavorite,
	)
	var i UserSessionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateName,
		&i.TemplateKey,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.UseCount,
		&i.IsFavorite,
	)
	return i, err
}

const deleteUserSessionTemplate = `-- name: DeleteUserSessionTemplate :exec
DELETE FROM user_session_templates
WHERE id = ? AND user_id = ?
`

type DeleteUserSessionTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteUserSessionTemplate(ctx context.Context, arg DeleteUserSessionTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessionTemplate, arg.ID, arg.UserID)
	return err
}

const getTemplateUseCount = `-- name: GetTemplateUseCount :one
SELECT use_count FROM user_session_templates
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetTemplateUseCountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTemplateUseCount(ctx context.Context, arg GetTemplateUseCountParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getTemplateUseCount, arg.ID, arg.UserID)
	var use_count sql.NullInt64
	err := row.Scan(&use_count)
	return use_count, err
}

const getUserSessionTemplate = `-- name: GetUserSessionTemplate :one
SELECT id, user_id, template_name, template_key, config_json, created_at, updated_at, last_used_at, use_count, is_favorite FROM user_session_templates
WHERE id = ? AND user_id = ?
LIMIT 1
`

type GetUserSessionTemplateParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetUserSessionTemplate(ctx context.Context, arg GetUserSessionTemplateParams) (UserSessionTemplate, error) {
	row := q.db.QueryRowContext(ctx, getUserSessionTemplate, arg.ID, arg.UserID)
	var i UserSessionTemplate
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TemplateName,
		&i.TemplateKey,
		&i.ConfigJson,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.UseCount,
		&i.IsFavorite,
	)
	return i, err
}

const incrementTemplateUseCount = `-- name: IncrementTemplateUseCount :exec
UPDATE user_session_templates
SET 
    use_count = use_count + 1,
    last_used_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type IncrementTemplateUseCountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) IncrementTemplateUseCount(ctx context.Context, arg IncrementTemplateUseCountParams) error {
	_, err := q.db.ExecContext(ctx, incrementTemplateUseCount, arg.ID, arg.UserID)
	return err
}

const listFavoriteTemplates = `-- name: ListFavoriteTemplates :many
SELECT id, user_id, template_name, template_key, config_json, created_at, updated_at, last_used_at, use_count, is_favorite FROM user_session_templates
WHERE user_id = ? AND is_favorite = 1
ORDER BY last_used_at DESC, created_at DESC
`

func (q *Queries) ListFavoriteTemplates(ctx context.Context, userID int64) ([]UserSessionTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listFavoriteTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSessionTemplate{}
	for rows.Next() {
		var i UserSessionTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateName,
			&i.TemplateKey,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.UseCount,
			&i.IsFavorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessionTemplates = `-- name: ListUserSessionTemplates :many
SELECT id, user_id, template_name, template_key, config_json, created_at, updated_at, last_used_at, use_count, is_favorite FROM user_session_templates
WHERE user_id = ?
ORDER BY is_favorite DESC, last_used_at DESC, created_at DESC
`

func (q *Queries) ListUserSessionTemplates(ctx context.Context, userID int64) ([]UserSessionTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listUserSessionTemplates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSessionTemplate{}
	for rows.Next() {
		var i UserSessionTemplate
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateName,
			&i.TemplateKey,
			&i.ConfigJson,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.UseCount,
			&i.IsFavorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserSessionTemplate = `-- name: UpdateUserSessionTemplate :exec
UPDATE user_session_templates
SET 
    template_name = COALESCE(?, template_name),
    config_json = COALESCE(?, config_json),
    is_favorite = COALESCE(?, is_favorite),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateUserSessionTemplateParams struct {
	TemplateName string       `json:"template_name"`
	ConfigJson   string       `json:"config_json"`
	IsFavorite   sql.NullBool `json:"is_favorite"`
	ID           int64        `json:"id"`
	UserID       int64        `json:"user_id"`
}

func (q *Queries) UpdateUserSessionTemplate(ctx context.Context, arg UpdateUserSessionTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSessionTemplate,
		arg.TemplateName,
		arg.ConfigJson,
		arg.IsFavorite,
		arg.ID,
		arg.UserID,
	)
	return err
}
