// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_pattern_stats.sql

package repo

import (
	"context"
	"database/sql"
)

const getPatternsWithStats = `-- name: GetPatternsWithStats :many
SELECT p.id, p.title, p.description, ups.times_revised, ups.avg_confidence, ups.last_revised_at
FROM patterns p
LEFT JOIN user_pattern_stats ups ON p.id = ups.pattern_id AND ups.user_id = ?
ORDER BY p.title
`

type GetPatternsWithStatsRow struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Description   sql.NullString `json:"description"`
	TimesRevised  sql.NullInt64  `json:"times_revised"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastRevisedAt sql.NullString `json:"last_revised_at"`
}

func (q *Queries) GetPatternsWithStats(ctx context.Context, userID int64) ([]GetPatternsWithStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPatternsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPatternsWithStatsRow{}
	for rows.Next() {
		var i GetPatternsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TimesRevised,
			&i.AvgConfidence,
			&i.LastRevisedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPatternStats = `-- name: GetUserPatternStats :one
SELECT id, user_id, pattern_id, times_revised, avg_confidence, last_revised_at FROM user_pattern_stats
WHERE user_id = ? AND pattern_id = ?
LIMIT 1
`

type GetUserPatternStatsParams struct {
	UserID    int64 `json:"user_id"`
	PatternID int64 `json:"pattern_id"`
}

func (q *Queries) GetUserPatternStats(ctx context.Context, arg GetUserPatternStatsParams) (UserPatternStat, error) {
	row := q.db.QueryRowContext(ctx, getUserPatternStats, arg.UserID, arg.PatternID)
	var i UserPatternStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PatternID,
		&i.TimesRevised,
		&i.AvgConfidence,
		&i.LastRevisedAt,
	)
	return i, err
}

const getWeakestPattern = `-- name: GetWeakestPattern :one
SELECT ups.id, ups.user_id, ups.pattern_id, ups.times_revised, ups.avg_confidence, ups.last_revised_at, p.title as pattern_title
FROM user_pattern_stats ups
JOIN patterns p ON ups.pattern_id = p.id
WHERE ups.user_id = ?
ORDER BY ups.avg_confidence ASC
LIMIT 1
`

type GetWeakestPatternRow struct {
	ID            int64          `json:"id"`
	UserID        int64          `json:"user_id"`
	PatternID     int64          `json:"pattern_id"`
	TimesRevised  sql.NullInt64  `json:"times_revised"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastRevisedAt sql.NullString `json:"last_revised_at"`
	PatternTitle  string         `json:"pattern_title"`
}

func (q *Queries) GetWeakestPattern(ctx context.Context, userID int64) (GetWeakestPatternRow, error) {
	row := q.db.QueryRowContext(ctx, getWeakestPattern, userID)
	var i GetWeakestPatternRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PatternID,
		&i.TimesRevised,
		&i.AvgConfidence,
		&i.LastRevisedAt,
		&i.PatternTitle,
	)
	return i, err
}

const listUserPatternStats = `-- name: ListUserPatternStats :many
SELECT id, user_id, pattern_id, times_revised, avg_confidence, last_revised_at FROM user_pattern_stats
WHERE user_id = ?
ORDER BY avg_confidence ASC
`

func (q *Queries) ListUserPatternStats(ctx context.Context, userID int64) ([]UserPatternStat, error) {
	rows, err := q.db.QueryContext(ctx, listUserPatternStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPatternStat{}
	for rows.Next() {
		var i UserPatternStat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PatternID,
			&i.TimesRevised,
			&i.AvgConfidence,
			&i.LastRevisedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPatternStats = `-- name: UpsertUserPatternStats :one
INSERT INTO user_pattern_stats (user_id, pattern_id, times_revised, avg_confidence, last_revised_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(user_id, pattern_id) DO UPDATE SET
    times_revised = excluded.times_revised,
    avg_confidence = excluded.avg_confidence,
    last_revised_at = excluded.last_revised_at
RETURNING id, user_id, pattern_id, times_revised, avg_confidence, last_revised_at
`

type UpsertUserPatternStatsParams struct {
	UserID        int64          `json:"user_id"`
	PatternID     int64          `json:"pattern_id"`
	TimesRevised  sql.NullInt64  `json:"times_revised"`
	AvgConfidence sql.NullInt64  `json:"avg_confidence"`
	LastRevisedAt sql.NullString `json:"last_revised_at"`
}

func (q *Queries) UpsertUserPatternStats(ctx context.Context, arg UpsertUserPatternStatsParams) (UserPatternStat, error) {
	row := q.db.QueryRowContext(ctx, upsertUserPatternStats,
		arg.UserID,
		arg.PatternID,
		arg.TimesRevised,
		arg.AvgConfidence,
		arg.LastRevisedAt,
	)
	var i UserPatternStat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PatternID,
		&i.TimesRevised,
		&i.AvgConfidence,
		&i.LastRevisedAt,
	)
	return i, err
}
